---
title: "Research"
output: html_document
---
My research is centered around the intersection of production agriculture and the natural environment. Some selected research items are presented below; for a more comprehensive listing see my full [CV](files/CV.pdf).

* **Ramsey, S.M.**, Bergtold, J.S., Canales, E., and J. Williams (2019) "Effects of Farmers’ Yield-Risk Perceptions on Conservation Practice Adoption in Kansas". *Journal of Agricultural and Resource Economics*, 44(2):380-403.
<details>
  <summary>Abstract</summary>
      When considering adoption or intensification of existing conservation practices, farmers have unique, subjective views of the associated risks. These individual risk perceptions could have important implications for conservation adoption or intensification. As a result, traditional policy approaches to encourage conservation agriculture may be inefficient. This study examines conservation adoption, with special consideration given to yield-risk perceptions. We present a conceptual model of perceived yield risk and estimate bivariate probit models using survey data. Results indicate that positive practice perceptions, particularly with respect to soil fertility, and opportunities for on-farm trialing may encourage adoption.
</details>

* Sanderson, M.R., Bergtold, J.S., Caldas, M.M., Heier Stamm, J., **Ramsey, S.M.**, and J. Aistrup. (2018) "Climate change beliefs in an agricultural context: What is the role of values held by farming and non-farming groups?" *Climatic Change*, no. 150(3):259—272.
<details>
  <summary>Abstract</summary>Climate change in many agricultural contexts will increase tensions between farming and non-farming populations over adaptations in land use and water conservation strategies. How adequately these future tensions may be mitigated will be partially determined by each groups' beliefs about climate change. A voluminous literature shows that climate change beliefs are crucial for understanding engagement with climate change mitigation and adaptation strategies, and that values motivate climate change beliefs, but the role of values remains unclear, and comparisons of farming and non-farming populations are scant. We develop a model of climate change beliefs that integrates four main motivating factors - values, political ideology, knowledge, and worldview - and we explicitly
compare members of farming and non-farming populations in an agricultural watershed in the Central Great Plains, USA. Our findings highlight the role of held values in motivating climate change beliefs and point to areas of potential consensus and tension within and among members of these two groups. The results provide an empirical basis for developing future climate change engagement strategies in contexts of growing divides and conflicts among farming and non-farming groups.
</details>

* Bergtold, J.S., **Ramsey, S.M.**, Maddy, L., and J. Williams. (2017) "A review of economic considerations for cover crops as a conservation practice." *Renewable Agriculture and Food Systems*:1—15.
<details>
  <summary>Abstract</summary>Over the past few decades, farmers have increasingly integrated cover crops into their cropping systems. Cover-crop benefits can help a farmer to achieve sustainability or reduce negative environmental externalities, such as soil erosion or chemical runoff. However, the impact on farm economics will likely be the strongest incentive to adopt cover crops. These impacts can include farm profits, cash crop yields or both. This paper provides a review of covercrop adoption, production, risk and policy considerations from an economic perspective. These dimensions are examined through a review of cover-crop literature. This review was written to provide an overview of cover crops and their impacts on the farm business and the environment, especially with regard to economic considerations. Through increasing knowledge about cover crops, the intent here is to inform producers contemplating adoption and policy makers seeking to encourage adoption.
</details>

* Sanderson, M., Bergtold, J.S., Heier Stamm, J., Caldas, M., **and S.M. Ramsey**. (2017) “Bringing the social into social-hydrology: Application to conservation policy support in the Central Great Plains of Kansas, USA.” *Water Resources Research*, 53:6725—6743.
<details>
  <summary>Abstract</summary>Identifying means of empirically modeling the human component of a coupled, human-water system becomes critically important to further advances in sociohydrology. We develop a social-psychological model of environmental decision making that addresses four key challenges of incorporating social science into integrated models. We use the model to explain preferences for three conservation policies designed to conserve and protect water resources and aquatic ecosystems in the Smoky Hill River Basin, a semiarid agricultural region in the Central U.S. Great Plains. Further, we compare the model’s capacity to explain policy preferences among members of two groups in the River Basin: agricultural producers and members of nonfarming communities. We find that financial obligation is the strongest and most consistent explanation of support for conservation policies among members of both groups. We also find that policy support is grounded in cultural values—deeply held ideas about right and wrong. Environmental values are particularly important explanations of policy support. The constellations of values invoked to make decisions about policies, and the social-psychological pathways linking values to policy support, can vary across policies and types of agents (farmers and nonfarmers). We discuss the implications of the results for future research in sociohydrology.
</details>